export const enTranslations = {
  common: {
    appName: "BHC Jobs",
    search: "Search",
    jobs: "Jobs",
    profile: "Profile",
    home: "Home",
    favorites: "Favorites",
    settings: "Settings",
    language: "Language",
    theme: "Theme",
    logout: "Sign Out",
    cancel: "Cancel",
    confirm: "Confirm",
    save: "Save",
    edit: "Edit",
    delete: "Delete",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    retry: "Retry",
    apply: "Apply",
    view: "View",
    close: "Close",
    welcome: "Welcome",
    welcomeBack: "Welcome back!",
  },
  auth: {
    signIn: "Sign In",
    signUp: "Sign Up",
    phoneNumber: "Phone Number",
    mobileNumber: "Mobile Number",
    password: "Password",
    confirmPassword: "Confirm Password",
    forgotPassword: "Forgot Your Password?",
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: "Already have an account?",
    createAccount: "Create Account",
    verifyOtp: "Verify OTP",
    enterOtp: "Enter the 6-digit code sent to your phone",
    resendOtp: "Resend Code",
    otpSent: "OTP sent successfully",
    verificationFailed: "Verification Failed",
    networkError: "Network Error",
    loginFailed: "Login Failed",
    loginSuccess: "Login successful",
    invalidCredentials: "Invalid credentials",
    pleaseEnterPhonePassword: "Please enter phone and password",
    fullName: "Full Name",
    email: "Email Address",
    passport: "Passport Number",
    dateOfBirth: "Date of Birth",
    gender: "Gender",
    required: "Required",
    passwordsNotMatch: "Passwords do not match",
    accountCreated: "Account Created",
    verifyPhone: "Please verify your phone number",
    registrationFailed: "Registration Failed",
    somethingWentWrong: "Something went wrong",
    enterCompleteOtp: "Please enter the complete 4-digit OTP",
    phoneVerified: "Phone verified successfully!",
    pleaseFillRequired: "Please fill in all required fields",
    enterFullName: "Enter your full name",
    createPassword: "Create a password",
    repeatPassword: "Repeat your password",
    enterPassport: "Enter passport number",
    selectDate: "Select date",
    selectGender: "Select",
  },
  home: {
    welcome: "Welcome to BHC Jobs",
    subtitle: "Build your profile, explore and apply to your favourite jobs",
    featuredJobs: "Featured Jobs",
    recentJobs: "Recent Jobs",
    viewAll: "View All",
    noJobs: "No jobs available",
    searchPlaceholder: "Search job title or company",
    locationPlaceholder: "Location",
    hiUser: "Hi, {{name}}",
    signIn: "Sign In",
  },
  jobs: {
    jobDetails: "Job Details",
    company: "Company",
    salary: "Salary",
    deadline: "Application Deadline",
    experience: "Experience",
    education: "Education",
    requirements: "Requirements",
    benefits: "Benefits",
    benefitsProvided: "Benefits Provided:",
    applyNow: "Apply Now",
    applied: "Applied",
    saved: "Saved",
    expired: "Expired",
    allJobs: "All Jobs",
    positionsAvailable: "{{count}} positions available",
    companyOverview: "Company Overview",
    jobDescription: "Job Description",
    jobResponsibility: "Job Responsibility",
    additionalRequirements: "Additional Requirements",
    otherBenefits: "Other Benefits",
    jobInformation: "Job Information",
    workingHours: "Working Hours:",
    hoursPerDay: "{{hours}} hours/day",
    gender: "Gender:",
    any: "Any",
    ageRequirement: "Age Requirement:",
    years: "Years",
    vacancy: "Vacancy:",
    employmentStatus: "Employment Status:",
    hardSkills: "Hard Skills:",
    softSkills: "Soft Skills:",
    languages: "Languages:",
    recommendedJobs: "Recommended Jobs for You",
  },
  favorites: {
    yourFavorites: "Your Favorites",
    savedJobs: "{{count}} saved jobs",
    noFavorites: "No favorite jobs yet",
  },
  search: {
    findJobs: "Find Jobs",
    searchPlaceholder: "Search job title, company...",
    recentSearches: "Recent Searches",
    jobCategories: "Job Categories",
  },
  profile: {
    myResume: "My Resume",
    savedJobs: "Saved Jobs",
    jobAlerts: "Job Alerts",
    helpCenter: "Help Center",
    blog: "Blog",
    editProfile: "Edit Profile",
    guestUser: "Guest User",
    noEmail: "No email provided",
    logoutConfirm: "Are you sure you want to sign out?",
    logoutSuccess: "You have been signed out successfully",
    logoutError: "Something went wrong during sign out",
    languageChanged: "Language changed successfully",
    blogError: "Unable to open blog link",
  },
  onboarding: {
    getStarted: "Get Started",
    newHere: "New here?",
    createAccountPrompt: "Create Account",
    description:
      "Build your profile, explore and apply to your favourite jobs and get contracted by employers immediately.",
  },
  theme: {
    light: "Light",
    dark: "Dark",
    system: "System Default",
    themeChanged: "Theme changed successfully",
  },
} as const;
