export const bnTranslations = {
  common: {
    appName: "বিএইচসি জবস",
    search: "অনুসন্ধান",
    jobs: "চাকরি",
    profile: "প্রোফাইল",
    home: "হোম",
    favorites: "প্রিয়",
    settings: "সেটিংস",
    language: "ভাষা",
    theme: "থিম",
    logout: "সাইন আউট",
    cancel: "বাতিল",
    confirm: "নিশ্চিত",
    save: "সংরক্ষণ",
    edit: "সম্পাদনা",
    delete: "মুছুন",
    loading: "লোড হচ্ছে...",
    error: "ত্রুটি",
    success: "সফল",
    retry: "আবার চেষ্টা করুন",
    apply: "আবেদন করুন",
    view: "দেখুন",
    close: "বন্ধ",
    welcome: "স্বাগতম",
    welcomeBack: "আবার স্বাগতম!",
  },
  auth: {
    signIn: "সাইন ইন",
    signUp: "সাইন আপ",
    phoneNumber: "ফোন নম্বর",
    mobileNumber: "মোবাইল নম্বর",
    password: "পাসওয়ার্ড",
    confirmPassword: "পাসওয়ার্ড নিশ্চিত করুন",
    forgotPassword: "পাসওয়ার্ড ভুলে গেছেন?",
    dontHaveAccount: "অ্যাকাউন্ট নেই?",
    alreadyHaveAccount: "ইতিমধ্যে অ্যাকাউন্ট আছে?",
    createAccount: "অ্যাকাউন্ট তৈরি করুন",
    verifyOtp: "ওটিপি যাচাই করুন",
    enterOtp: "আপনার ফোনে পাঠানো ৬-সংখ্যার কোডটি লিখুন",
    resendOtp: "কোড আবার পাঠান",
    otpSent: "ওটিপি সফলভাবে পাঠানো হয়েছে",
    verificationFailed: "যাচাই ব্যর্থ হয়েছে",
    networkError: "নেটওয়ার্ক ত্রুটি",
    loginFailed: "লগইন ব্যর্থ",
    loginSuccess: "লগইন সফল",
    invalidCredentials: "অবৈধ শংসাপত্র",
    pleaseEnterPhonePassword: "অনুগ্রহ করে ফোন এবং পাসওয়ার্ড লিখুন",
    fullName: "পূর্ণ নাম",
    email: "ইমেইল ঠিকানা",
    passport: "পাসপোর্ট নম্বর",
    dateOfBirth: "জন্ম তারিখ",
    gender: "লিঙ্গ",
    required: "আবশ্যক",
    passwordsNotMatch: "পাসওয়ার্ড মিলছে না",
    accountCreated: "অ্যাকাউন্ট তৈরি হয়েছে",
    verifyPhone: "অনুগ্রহ করে আপনার ফোন নম্বর যাচাই করুন",
    registrationFailed: "নিবন্ধন ব্যর্থ",
    somethingWentWrong: "কিছু ভুল হয়েছে",
    enterCompleteOtp: "অনুগ্রহ করে সম্পূর্ণ ৪-সংখ্যার ওটিপি লিখুন",
    phoneVerified: "ফোন সফলভাবে যাচাই করা হয়েছে!",
    pleaseFillRequired: "অনুগ্রহ করে সমস্ত আবশ্যক ক্ষেত্র পূরণ করুন",
    enterFullName: "আপনার পূর্ণ নাম লিখুন",
    createPassword: "একটি পাসওয়ার্ড তৈরি করুন",
    repeatPassword: "আপনার পাসওয়ার্ড পুনরাবৃত্তি করুন",
    enterPassport: "পাসপোর্ট নম্বর লিখুন",
    selectDate: "তারিখ নির্বাচন করুন",
    selectGender: "নির্বাচন করুন",
  },
  home: {
    welcome: "বিএইচসি জবস-এ স্বাগতম",
    subtitle: "আপনার প্রোফাইল তৈরি করুন, চাকরি অন্বেষণ করুন এবং আবেদন করুন",
    featuredJobs: "বৈশিষ্ট্যযুক্ত চাকরি",
    recentJobs: "সাম্প্রতিক চাকরি",
    viewAll: "সব দেখুন",
    noJobs: "কোন চাকরি পাওয়া যায়নি",
    searchPlaceholder: "চাকরির শিরোনাম বা কোম্পানি অনুসন্ধান করুন",
    locationPlaceholder: "অবস্থান",
    hiUser: "হ্যালো, {{name}}",
    signIn: "সাইন ইন",
  },
  jobs: {
    jobDetails: "চাকরির বিবরণ",
    company: "কোম্পানি",
    salary: "বেতন",
    deadline: "আবেদনের শেষ তারিখ",
    experience: "অভিজ্ঞতা",
    education: "শিক্ষা",
    requirements: "প্রয়োজনীয়তা",
    benefits: "সুবিধা",
    benefitsProvided: "সুবিধা প্রদান করা হয়:",
    applyNow: "এখন আবেদন করুন",
    applied: "আবেদন করা হয়েছে",
    saved: "সংরক্ষিত",
    expired: "মেয়াদ শেষ",
    allJobs: "সব চাকরি",
    positionsAvailable: "{{count}}টি পদ খালি আছে",
    companyOverview: "কোম্পানি ওভারভিউ",
    jobDescription: "চাকরির বিবরণ",
    jobResponsibility: "চাকরির দায়িত্ব",
    additionalRequirements: "অতিরিক্ত প্রয়োজনীয়তা",
    otherBenefits: "অন্যান্য সুবিধা",
    jobInformation: "চাকরির তথ্য",
    workingHours: "কর্মঘণ্টা:",
    hoursPerDay: "প্রতিদিন {{hours}} ঘণ্টা",
    gender: "লিঙ্গ:",
    any: "যেকোনো",
    ageRequirement: "বয়সের প্রয়োজনীয়তা:",
    years: "বছর",
    vacancy: "শূন্যপদ:",
    employmentStatus: "চাকরির অবস্থা:",
    hardSkills: "কঠিন দক্ষতা:",
    softSkills: "নরম দক্ষতা:",
    languages: "ভাষা:",
    recommendedJobs: "আপনার জন্য প্রস্তাবিত চাকরি",
  },
  favorites: {
    yourFavorites: "আপনার পছন্দ",
    savedJobs: "{{count}}টি সংরক্ষিত চাকরি",
    noFavorites: "এখনো কোনো পছন্দের চাকরি নেই",
  },
  search: {
    findJobs: "চাকরি খুঁজুন",
    searchPlaceholder: "চাকরির শিরোনাম, কোম্পানি অনুসন্ধান করুন...",
    recentSearches: "সাম্প্রতিক অনুসন্ধান",
    jobCategories: "চাকরির বিভাগ",
  },
  profile: {
    myResume: "আমার জীবনবৃত্তান্ত",
    savedJobs: "সংরক্ষিত চাকরি",
    jobAlerts: "চাকরির সতর্কতা",
    helpCenter: "সহায়তা কেন্দ্র",
    blog: "ব্লগ",
    editProfile: "প্রোফাইল সম্পাদনা",
    guestUser: "অতিথি ব্যবহারকারী",
    noEmail: "কোন ইমেইল প্রদান করা হয়নি",
    logoutConfirm: "আপনি কি সাইন আউট করতে চান?",
    logoutSuccess: "আপনি সফলভাবে সাইন আউট করেছেন",
    logoutError: "সাইন আউটের সময় কিছু ভুল হয়েছে",
    languageChanged: "ভাষা সফলভাবে পরিবর্তন করা হয়েছে",
    blogError: "ব্লগ লিঙ্ক খুলতে অক্ষম",
  },
  onboarding: {
    getStarted: "শুরু করুন",
    newHere: "নতুন এখানে?",
    createAccountPrompt: "অ্যাকাউন্ট তৈরি করুন",
    description:
      "আপনার প্রোফাইল তৈরি করুন, চাকরি অন্বেষণ করুন এবং আবেদন করুন এবং নিয়োগকর্তাদের সাথে সাথে চুক্তি করুন।",
  },
  theme: {
    light: "লাইট",
    dark: "ডার্ক",
    system: "সিস্টেম ডিফল্ট",
    themeChanged: "থিম সফলভাবে পরিবর্তন করা হয়েছে",
  },
} as const;
