export const arTranslations = {
  common: {
    appName: "بي اتش سي جوبس",
    search: "بحث",
    jobs: "وظائف",
    profile: "الملف الشخصي",
    home: "الرئيسية",
    favorites: "المفضلة",
    settings: "الإعدادات",
    language: "اللغة",
    theme: "المظهر",
    logout: "تسجيل الخروج",
    cancel: "إلغاء",
    confirm: "تأكيد",
    save: "حفظ",
    edit: "تعديل",
    delete: "حذف",
    loading: "جاري التحميل...",
    error: "خطأ",
    success: "نجاح",
    retry: "إعادة المحاولة",
    apply: "تقديم",
    view: "عرض",
    close: "إغلاق",
    welcome: "مرحباً",
    welcomeBack: "مرحباً بعودتك!",
  },
  auth: {
    signIn: "تسجيل الدخول",
    signUp: "إنشاء حساب",
    phoneNumber: "رقم الهاتف",
    mobileNumber: "رقم الجوال",
    password: "كلمة المرور",
    confirmPassword: "تأكيد كلمة المرور",
    forgotPassword: "نسيت كلمة المرور؟",
    dontHaveAccount: "ليس لديك حساب؟",
    alreadyHaveAccount: "لديك حساب بالفعل؟",
    createAccount: "إنشاء حساب جديد",
    verifyOtp: "التحقق من الرمز",
    enterOtp: "أدخل الرمز المكون من 6 أرقام المرسل إلى هاتفك",
    resendOtp: "إعادة إرسال الرمز",
    otpSent: "تم إرسال الرمز بنجاح",
    verificationFailed: "فشل التحقق",
    networkError: "خطأ في الشبكة",
    loginFailed: "فشل تسجيل الدخول",
    loginSuccess: "تم تسجيل الدخول بنجاح",
    invalidCredentials: "بيانات الاعتماد غير صالحة",
    pleaseEnterPhonePassword: "الرجاء إدخال الهاتف وكلمة المرور",
    fullName: "الاسم الكامل",
    email: "عنوان البريد الإلكتروني",
    passport: "رقم جواز السفر",
    dateOfBirth: "تاريخ الميلاد",
    gender: "الجنس",
    required: "مطلوب",
    passwordsNotMatch: "كلمات المرور غير متطابقة",
    accountCreated: "تم إنشاء الحساب",
    verifyPhone: "يرجى التحقق من رقم هاتفك",
    registrationFailed: "فشل التسجيل",
    somethingWentWrong: "حدث خطأ ما",
    enterCompleteOtp: "الرجاء إدخال الرمز المكون من 4 أرقام بالكامل",
    phoneVerified: "تم التحقق من الهاتف بنجاح!",
  },
  home: {
    welcome: "مرحباً بك في بي اتش سي جوبس",
    subtitle: "أنشئ ملفك الشخصي، استكشف وقدم على وظائفك المفضلة",
    featuredJobs: "وظائف مميزة",
    recentJobs: "وظائف حديثة",
    viewAll: "عرض الكل",
    noJobs: "لا توجد وظائف متاحة",
    searchPlaceholder: "البحث عن وظيفة أو شركة",
    locationPlaceholder: "الموقع",
    hiUser: "مرحباً، {{name}}",
    signIn: "تسجيل الدخول",
  },
  jobs: {
    jobDetails: "تفاصيل الوظيفة",
    company: "الشركة",
    salary: "الراتب",
    deadline: "الموعد النهائي للتقديم",
    experience: "الخبرة",
    education: "التعليم",
    requirements: "المتطلبات",
    benefits: "المزايا",
    benefitsProvided: "المزايا المقدمة:",
    applyNow: "قدم الآن",
    applied: "تم التقديم",
    saved: "تم الحفظ",
    expired: "منتهي الصلاحية",
    allJobs: "جميع الوظائف",
    positionsAvailable: "{{count}} وظائف شاغرة",
    companyOverview: "نظرة عامة على الشركة",
    jobDescription: "وصف الوظيفة",
    jobResponsibility: "المسؤوليات الوظيفية",
    additionalRequirements: "متطلبات إضافية",
    otherBenefits: "مزايا أخرى",
    jobInformation: "معلومات الوظيفة",
    workingHours: "ساعات العمل:",
    hoursPerDay: "{{hours}} ساعة/يوم",
    gender: "الجنس:",
    any: "أي",
    ageRequirement: "متطلبات العمر:",
    years: "سنة",
    vacancy: "الشاغر:",
    employmentStatus: "حالة التوظيف:",
    hardSkills: "المهارات الصلبة:",
    softSkills: "المهارات الناعمة:",
    languages: "اللغات:",
    recommendedJobs: "وظائف موصى بها لك",
  },
  favorites: {
    yourFavorites: "المفضلة",
    savedJobs: "{{count}} وظائف محفوظة",
    noFavorites: "لا توجد وظائف مفضلة بعد",
  },
  search: {
    findJobs: "البحث عن وظائف",
    searchPlaceholder: "البحث عن وظيفة أو شركة...",
    recentSearches: "عمليات البحث الأخيرة",
    jobCategories: "فئات الوظائف",
  },
  profile: {
    myResume: "سيرتي الذاتية",
    savedJobs: "الوظائف المحفوظة",
    jobAlerts: "تنبيهات الوظائف",
    helpCenter: "مركز المساعدة",
    blog: "المدونة",
    editProfile: "تعديل الملف الشخصي",
    guestUser: "زائر",
    noEmail: "لا يوجد بريد إلكتروني",
    logoutConfirm: "هل أنت متأكد من تسجيل الخروج؟",
    logoutSuccess: "تم تسجيل الخروج بنجاح",
    logoutError: "حدث خطأ أثناء تسجيل الخروج",
    languageChanged: "تم تغيير اللغة بنجاح",
    blogError: "تعذر فتح رابط المدونة",
  },
  onboarding: {
    getStarted: "ابدأ الآن",
    newHere: "جديد هنا؟",
    createAccountPrompt: "إنشاء حساب",
    description:
      "أنشئ ملفك الشخصي، استكشف وقدم على وظائفك المفضلة واحصل على عقود مع أصحاب العمل فوراً.",
  },
  theme: {
    light: "فاتح",
    dark: "داكن",
    system: "افتراضي النظام",
    themeChanged: "تم تغيير المظهر بنجاح",
  },
} as const;
